# Generated by Django 5.1.1 on 2024-10-15 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_task_text', models.CharField(max_length=200)),
                ('plan_task_completed', models.BooleanField()),
                ('plan_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDjDemo1.plan_tasks')),
            ],
        ),
    ]
