# Generated by Django 5.1.1 on 2024-10-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjDemo1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categories_name_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=125)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=6)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('taste_name_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('test_name', models.CharField(choices=[('EQ_EI', 'EQ_EI'), ('IQ_IT', 'IQ_IT'), ('SI', 'SI'), ('GKt', 'GKt'), ('PT', 'PT'), ('JT_RT', 'JT_RT'), ('AA_MT', 'AA_MT'), ('CT', 'CT')], default='EQ_EI', max_length=10)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ans_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_text', models.TextField()),
                ('score_value', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='AppDjDemo1.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('snt_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('subcategory_name', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='AppDjDemo1.category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='AppDjDemo1.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='AppDjDemo1.test'),
        ),
    ]
