# Generated by Django 5.1.1 on 2024-10-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjDemo1', '0002_category_question_test_answer_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('none', 'None'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=6),
        ),
    ]
